### ISSUE TITLE
ccaa的网页端口6080在哪更换？

### ISSUE THREAD

**Issue by sjkgames** [helloxz/ccaa#10]
是ngix还是apache搭建的呢？在哪个文件夹下，小鸡被墙了，不方便查找。。请教一下大佬。

**Comment by helloxz** [comment]
用的是Caddy，这个问题参考帮助文档：[管理 & 维护 - 文件说明](https://www.xiaoz.me/doc/doc-ccaa/preserve)可解决。

**Comment by sjkgames** [comment]
我在Caddy里更改了端口为80，或者其他端口，都无法访问，只能是6080的时候才可以访问。



------------------ 原始邮件 ------------------
发件人: "Mr.zou"<notifications@github.com>; 
发送时间: 2019年6月5日(星期三) 下午5:23
收件人: "helloxz/ccaa"<ccaa@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [helloxz/ccaa] ccaa的网页端口6080在哪更换？ (#10)




用的是Caddy，这个问题参考帮助文档：管理&维护-文件说明可解决。

**Comment by helloxz** [comment]
1. 修改端口后需要重启ccaa：`ccaa restart`
2. 检查80端口是否被其它进程占用：`netstat -apn|grep '80'`
3. 设置了新端口，记得你服务器的防火墙、安全组将对应端口放行

**Comment by sjkgames** [comment]
谢谢大佬，忘记关防火墙了，OK



------------------ 原始邮件 ------------------
发件人: "Mr.zou"<notifications@github.com>; 
发送时间: 2019年6月5日(星期三) 晚上11:48
收件人: "helloxz/ccaa"<ccaa@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [helloxz/ccaa] ccaa的网页端口6080在哪更换？ (#10)



 
修改端口后需要重启ccaa：ccaa restart
 
检查80端口是否被其它进程占用：netstat -apn|grep '80'
 
设置了新端口，记得你服务器的防火墙、安全组将对应端口放行
