### ISSUE TITLE
在线预览功能在哪儿？

### ISSUE THREAD

**Issue by jonsonjordan** [helloxz/ccaa#11]
没找到相关功能按钮，看博客也没有太多介绍

**Comment by helloxz** [comment]
请问阁下需要预览什么？更多的说明应该查看帮助文档：[https://www.xiaoz.me/doc/doc-ccaa](https://www.xiaoz.me/doc/doc-ccaa)

**Comment by jonsonjordan** [comment]
居然是双击播放，我还在找播放按钮，打扰打扰
