### ISSUE TITLE
一直认证失败是怎么回事

### ISSUE THREAD

**Issue by wengzuyang** [helloxz/ccaa#12]
![image](https://user-images.githubusercontent.com/11473283/60149785-77e27180-9808-11e9-823a-9c7aa4315dfc.png)

**Comment by helloxz** [comment]
系统设置 - AriaNG设置 - RPC - RPC密钥设置一下。这些内容在帮助文档中都有提到，建议通读一遍帮助文档： [https://www.xiaoz.me/doc/doc-ccaa/](https://www.xiaoz.me/doc/doc-ccaa/)

![](https://imgurl.org/upload/1810/0262be6ae3e9dcc2.png)

**Comment by wengzuyang** [comment]
可以了，谢谢

**Comment by helloxz** [comment]
不客气
