### ISSUE TITLE
在ccaa目录下没有找到aria2.log

### ISSUE THREAD

**Issue by ReddotCleaner** [helloxz/ccaa#22]
在etc/ccaa目录下没有找到aria2.log，是否在其他目录，还是去掉了log？ aria2log排查一些问题还是很有帮助的。感谢

**Comment by helloxz** [comment]
2.0开始日志文件有所变更,日志位于`/var/log/aria2.log`，这是帮助文档：[https://www.yuque.com/helloz/ccaa/preserve](https://www.yuque.com/helloz/ccaa/preserve)

**Comment by ReddotCleaner** [comment]
感谢解答
