### ISSUE TITLE
更新2.1以后打不开AriaNg页面

### ISSUE THREAD

**Issue by kuaichongdian** [helloxz/ccaa#28]
之前的2.0能正常安装使用
更新2.1以后打不开AriaNg页面
运行脚本能正常安装，不过用ccaa status查看状态一直是not running，
也用过ccaa start和restart命令 再次查看状态也是not running
我有2个不同服务商的vps都是这情况（debian9+ 64位）
打开http://我的ip:6080/页面 显示如下
————————————————————
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
————————————————————

**Comment by helloxz** [comment]
您是怎么更新的呢？得先卸载，然后重新安装2.1

**Comment by kuaichongdian** [comment]
你好 我的确是卸载了旧版再安装的 其中一个服务器我还重装了系统再安装2.1 但结果还是这样
我也是小白~~~我在服务器那里点了rebuild 应该就会完全格式化再重装 没什么残留吧（rebuild的时候我选的是同一个系统版本 debian9.9 64）

**Comment by helloxz** [comment]
ccaa status，看下运行没有呢？直接执行`/usr/sbin/ccaa_web`报错不？

**Comment by kuaichongdian** [comment]
emmm我在邮件回你了 但是发现这没有同步更新 再这里再回复一下 给遇到相同问题的小伙伴做参考
————————————————————
status 没运行 ccaa start 之后 还是没运行
输入/usr/sbin/ccaa_web 没反应（就是直接让我继续输入命令 没报错 没反馈）
我又从新安装了一次 发现脚本运行后 一开头有这两句话（之前已执行apt-get -y install curl）
不知道这是不是问题所在

-------------------------------------------------------------
检测通过，即将开始安装。
-------------------------------------------------------------
/dev/fd/63: line 45: sudo: command not found
/dev/fd/63: line 46: sudo: command not found

**Comment by helloxz** [comment]
执行名：`apt-get install sudo -y`，然后卸载再安装一次。

**Comment by helloxz** [comment]
另外你在安装的时候最好用root身份来执行

**Comment by kuaichongdian** [comment]
膜拜大佬 能正常运行了~~~感谢

**Comment by helloxz** [comment]
不客气
