### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by Seversh** [helloxz/ccaa#29]
Debian9，2台小鸡都是这个错误

/dev/fd/63: line 1: 500:: command not found

**Comment by quancs** [comment]
同样的错误

**Comment by helloxz** [comment]
apt-get -y install sudo后再试试

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Seversh** [comment]
sudo is already the newest version (1.8.19p1-2.1+deb9u2)

不过可以正常安装了
