### ISSUE TITLE
文档挂了？

### ISSUE THREAD

**Issue by hanzichi** [helloxz/ccaa#3]
文档挂了？

**Comment by helloxz** [comment]
不好意思，是我文档地址写错了，正确的地址是：[https://doc.xiaoz.me/#/ccaa/](https://doc.xiaoz.me/#/ccaa/) ，感谢反馈，已修正。

**Comment by hanzichi** [comment]
给力回复

**Comment by hanzichi** [comment]
用了您的方法，下载 .torrent 文件，抱这个错误，能帮忙看下原因吗？

![image](https://user-images.githubusercontent.com/10890665/48115030-572ad300-e29c-11e8-8b06-29649b6ce680.png)

**Comment by hanzichi** [comment]
上面的情况是我先下了个 .torrent 文件，然后在下载页面上传该文件，貌似最后下载到服务器的也是个 .torrent 文件。然后我新找了个 magnet 开头的链接，这次下载是一动不动，也没报错。。。

**Comment by helloxz** [comment]
1. 首先找个热门的种子
2. 其次，点击文件的时候可以看到该种子做种状态，如果当前没有人分享做种，自然没有速度。

**Comment by hanzichi** [comment]
谢谢指导🙏

**Comment by hanzichi** [comment]
小额赞赏，不成敬意

**Comment by helloxz** [comment]
收到18.88，谢谢支持。

**Comment by hanzichi** [comment]
再请教下，下载完后，是点击这个下载到本地吗 

![image](https://user-images.githubusercontent.com/10890665/48116754-09b16480-e2a2-11e8-8e6a-e638f22e9969.png)

感觉有点慢啊。。有没有办法可以直接在 /admin 页面播放下载后到文件？

**Comment by helloxz** [comment]
1. 是点这个按钮下载
2. 推荐使用IDM、迅雷等多线程下载，可有效提高下载速度。

**Comment by hanzichi** [comment]
再请教下，通过这样的下载，和进入服务器后用 `aria2c xxx` 进行下载，结果是一样的吗？

**Comment by helloxz** [comment]
一样的，只是web方式方便操作和管理而已。
