### ISSUE TITLE
能否选择使用caddy而不是 ccaa_web?

### ISSUE THREAD

**Issue by sukanka** [helloxz/ccaa#31]
现在的脚本能够一键部署好aria2+AriaNg+filemanager, 确实十分方便，但是我希望能够通过域名访问ariaNg, 如 `ariang.mydomain.com` 而不是 `domain+port` 的形式。
而且我希望能够启用 https 支持，以前用caddy 是支持证书自动申请与续期的。但是现在的 ccaa_web 让我无从下手，不知道如何启用 https与直接使用域名访问。

**Comment by helloxz** [comment]
确实如你所说，`ccaa_web `是用golang单独写的，功能不如Caddy，这个我后面看能不能让用户自行选择。

**Comment by crazypeace** [comment]
你先学会怎么搭caddy, 配置域名等。

让caddy显示AriaNG的页面很简单。
```
you.domain
{
  root * /etc/ccaa
  file_server
}
```
https://zelikk.blogspot.com/2023/06/ariang-caddy-https-cdn.html
