### ISSUE TITLE
文件管理器404

### ISSUE THREAD

**Issue by benladen** [helloxz/ccaa#32]
404 page not found

什么原因呢，卸载老版本，安装的新版本

**Comment by helloxz** [comment]
1. `ccaa status`看下运行状态
2. 是安装新的方法安装的吗？什么操作系统？

**Comment by benladen** [comment]
> 1. `ccaa status`看下运行状态
> 2. 是安装新的方法安装的吗？什么操作系统？

已解决，是浏览器缓存的就ariang页面。

**Comment by helloxz** [comment]
好的，ariang是静态页面，部分浏览器可能会缓存。后期有问题请再反馈。
