### ISSUE TITLE
2.1版本ccaa start命令失效

### ISSUE THREAD

**Issue by NIAENGD** [helloxz/ccaa#36]
系统版本：Debian9 64位
ccaa start命令无法启动ccaa，输入后使用状态查看命令显示未启动。

root@NIAENGD:~# ccaa -v
2.1
root@NIAENGD:~# ccaa start
root@NIAENGD:~# ccaa status
Not running!

**Comment by helloxz** [comment]
参考文档：[https://www.yuque.com/helloz/ccaa/preserve](https://www.yuque.com/helloz/ccaa/preserve) 提供下日志文件：
CCAA产生的相关日志文件都位于/var/log/，路径如下：
• Aria2日志文件：aria2.log
• FileBrowser日志文件：filebrowser.log
• FileBrowser运行时产生的日志文件：fbrun.log
• ccaa_web运行产生的日志文件：ccaa_web.log

**Comment by NIAENGD** [comment]
日志表明问题并不是出在此软件上，现已解决，谢谢您的提醒
