### ISSUE TITLE
6080打开怎么加入认证？

### ISSUE THREAD

**Issue by freehehe** [helloxz/ccaa#37]
公网上被别人打开太容易社会性死亡了

**Comment by helloxz** [comment]
6080是AriaNG静态页面，不需要认证，您的担心是别人访问这个页面添加下载或删除任务吗？你可以换个浏览器测试，根本不会发生这种情况，除非你的Aria2 RPC密钥泄露。

获取 Outlook for Android<https://aka.ms/ghei36>
