### ISSUE TITLE
2.1版本浏览器页面不提示账号密码验证

### ISSUE THREAD

**Issue by UnknownObject000** [helloxz/ccaa#40]
用这个repo的README里的命令安装完ccaa以后打开6080端口的网页不会弹出输入用户名与密码的认证界面（弹窗），而是直接提示“错误：认证失败”。使用VPS和WSL反复安装测试，均如此。更换浏览器也无法解决问题。卸载重装无效。脚本运行过程中无报错。

**Comment by helloxz** [comment]
您直接在系统设置 - AriaNG设置 - 设置RPC密钥不就行了么，注意看文档。https://www.yuque.com/helloz/ccaa/install
![](https://cdn.nlark.com/yuque/0/2019/png/anonymous/1572855505381-734aeefd-f9bd-41c0-8e43-5216a70b2479.png)

**Comment by UnknownObject000** [comment]
不是RPC密钥，是网页的登录验证。就是用户名ccaa密码admin那个
