### ISSUE TITLE
一键安装脚本重启VPS后不能自启动

### ISSUE THREAD

**Issue by zhucaidan** [helloxz/ccaa#46]
使用的是一键安装脚本安装到VPS，系统是Centos7
重启VPS后不能自启动ccaa，必须手动执行ccaa start

请问如何能设置开机自启呢？或者在脚本增加一个添加开机启动项的选项

**Comment by helloxz** [comment]
您好，可以参考这个文档：https://www.yuque.com/helloz/ccaa/preserve#ef161d27 设置开机启动。
