### ISSUE TITLE
报错：/dev/fd/63: line 11: [: =: unary operator expected

### ISSUE THREAD

**Issue by kfen** [helloxz/ccaa#47]
报错：/dev/fd/63: line 11: [: =: unary operator expected

安装开始检测时提示这样报错，后面就一路失败了

debian9x64

**Comment by kfen** [comment]
![Uploading QQ图片20201218093451.png…]()

**Comment by kfen** [comment]
root@debian:/dev/fd# bash <(curl -Lsk https://raw.githubusercontent.com/helloxz/ccaa/master/ccaa.sh)
/dev/fd/63: line 11: [: =: unary operator expected

**Comment by crazypeace** [comment]
bash <(curl -Lsk https://git.io/ccaasudo.sh)

https://github.com/crazypeace/ccaa
