### ISSUE TITLE
文件管理在线预览mp4只有音频

### ISSUE THREAD

**Issue by oceanwave72** [helloxz/ccaa#5]
较大的mp4文件，在线播放只有音频加载出来。有人遇到这种情况么

**Comment by helloxz** [comment]
filemange部分视频编码无法播放，在线播放非常弱，如果播放视频推荐配合Plex：[CentOS 7安装Plex打造自己的家庭影音](https://www.xiaoz.me/archives/11607)

**Comment by oceanwave72** [comment]
多谢。
