### ISSUE TITLE
程序没启动

### ISSUE THREAD

**Issue by JKeita** [helloxz/ccaa#6]
/usr/bin/aria2c: /usr/bin/aria2c: cannot execute binary file
/usr/sbin/caddy: /usr/sbin/caddy: cannot execute binary file

**Comment by helloxz** [comment]
1. 先检查下`/usr/bin/aria2c` `/usr/sbin/caddy`这2个文件是否存在
2. 如果存在请赋予执行权限`x`再试一下（`chmod +x /usr/bin/aria2c`）
3. 如果以上都不行，请先执行卸载，然后再次安装。（注意：ccaa目前仅能用于CentOS系统）

**Comment by JKeita** [comment]
@helloxz 已解决，是32系统不行。

**Comment by helloxz** [comment]
好的，程序都是64位的，无法在32位运行。
